version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

    groups:
      packaging:
        applies-to: version-updates
        patterns:
          - build
          - hatch
          - hatchling
          - packaging

      mypy:
        applies-to: version-updates
        patterns:
          - mypy
          - mypy-*

    ignore:
    - dependency-name: ruff
      update-types:
        # Cut the frequency of linter Dependabot PRs.
        # Ruff is 0ver, so this ignores all non-"major" releases.
        - "version-update:semver-patch"

